project:
  type: website
  output-dir: docs

website:
  title: "Huvudsta Kappsegling & Kanot Klubb"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - Kappsegling.qmd
      - kanot.qmd
      - verkstad.qmd
      - medlemskap.qmd
      - kontakt.qmd

format:
  html:
    theme: sandstone
    css: styles.css
    toc: true



